// import { Patient } from "./TherapistType";

// export const MOCK_PATIENTS: Patient[] = [
//   {
//     id: 1,
//     name: "Alex Johnson",
//     sessionCount: 4,
//     progressPercent: 50,
//     status: "Active",
//     therapistId: 1,
//   },
//   {
//     id: 2,
//     name: "Emily Carter",
//     sessionCount: 15,
//     progressPercent: 50,
//     status: "Active",
//     therapistId: 1,
//   },
//   {
//     id: 3,
//     name: "Michael Smith",
//     sessionCount: 7,
//     progressPercent: 50,
//     status: "Active",
//     therapistId: 1,
//   },
//   {
//     id: 4,
//     name: "Sophia Brown",
//     sessionCount: 3,
//     progressPercent: 50,
//     status: "Inactive",
//     therapistId: 1,
//   },
//   {
//     id: 5,
//     name: "Liam Davis",
//     sessionCount: 6,
//     progressPercent: 50,
//     status: "Active",
//     therapistId: 2,
//   },
//   {
//     id: 6,
//     name: "Olivia Wilson",
//     sessionCount: 3,
//     progressPercent: 50,
//     status: "Active",
//     therapistId: 2,
//   },
//   {
//     id: 7,
//     name: "James Taylor",
//     sessionCount: 8,
//     progressPercent: 50,
//     status: "Inactive",
//     therapistId: 3,
//   },
//   {
//     id: 8,
//     name: "Isabella Martinez",
//     sessionCount: 6,
//     progressPercent: 50,
//     status: "Active",
//     therapistId: 3,
//   },
//   {
//     id: 9,
//     name: "Ethan Anderson",
//     sessionCount: 11,
//     progressPercent: 50,
//     status: "Inactive",
//     therapistId: 4,
//   },
//   {
//     id: 10,
//     name: "Ava Thomas",
//     sessionCount: 9,
//     progressPercent: 50,
//     status: "Active",
//     therapistId: 5,
//   },
// ];